[lorax]
debug = 1
sharedir = /usr/share/lorax
logdir = /home/munx64/improtant/HisnOS-Secure-Workstation

[output]
colors = 1
encoding = utf-8
ignorelist = /usr/share/lorax/ignorelist

[templates]
ramdisk = ramdisk.ltmpl

[compression]
type = xz
args = 
bcj = on

[compression.erofs]
type = zstd,8
args = -Ededupe,all-fragments -C 65536

