#!/usr/bin/env bash
# dracut/install-dracut-module.sh
#
# Installs the HisnOS dracut module into the running system and
# rebuilds the initramfs. Safe to re-run (idempotent).
#
# Usage: sudo bash install-dracut-module.sh [--dry-run] [--no-rebuild]
# =============================================================================
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODULE_SRC="${SCRIPT_DIR}/95hisnos"
MODULE_DST="/usr/lib/dracut/modules.d/95hisnos"

DRY_RUN=false
NO_REBUILD=false
for arg in "$@"; do
    case "$arg" in
        --dry-run)    DRY_RUN=true ;;
        --no-rebuild) NO_REBUILD=true ;;
    esac
done

G="\e[32m" Y="\e[33m" R="\e[31m" B="\e[36m" W="\e[1m" X="\e[0m"
log()  { echo -e "${B}[dracut-install]${X} $*"; }
ok()   { echo -e "${G}[dracut-install] ✔${X} $*"; }
warn() { echo -e "${Y}[dracut-install] ⚠${X} $*"; }
fail() { echo -e "${R}[dracut-install] ✘${X} $*"; exit 1; }
dry()  { echo -e "${Y}[DRY-RUN]${X} $*"; }

[[ "$(id -u)" -eq 0 ]] || fail "Must run as root"
[[ -d "$MODULE_SRC" ]] || fail "Module source not found: $MODULE_SRC"

# ─── Install module ───────────────────────────────────────────────────────────
log "Installing HisnOS dracut module (95hisnos)..."
if [[ "$DRY_RUN" == "true" ]]; then
    dry "mkdir -p $MODULE_DST"
    dry "rsync -a $MODULE_SRC/ $MODULE_DST/"
else
    mkdir -p "$MODULE_DST"
    rsync -a --delete "${MODULE_SRC}/" "${MODULE_DST}/"
    chmod +x "${MODULE_DST}"/*.sh 2>/dev/null || true
    ok "Module installed: $MODULE_DST"
fi

# ─── Create HisnOS config directory ──────────────────────────────────────────
log "Ensuring /etc/hisnos/..."
if [[ "$DRY_RUN" != "true" ]]; then
    mkdir -p /etc/hisnos
    # Create default cmdline policy if missing
    if [[ ! -f /etc/hisnos/cmdline-policy.conf ]]; then
        cat > /etc/hisnos/cmdline-policy.conf <<'EOF'
# HisnOS kernel cmdline policy
# Format: forbidden_arg=ARGNAME or strict_arg=ARGNAME
# Lines starting with # are comments.
#
# forbidden_arg — triggers safe-mode (non-strict) or halt (strict mode)
forbidden_arg=nosecurity
forbidden_arg=selinux=0
forbidden_arg=apparmor=0
forbidden_arg=ima_appraise=fix
forbidden_arg=init=/bin/sh
forbidden_arg=init=/bin/bash
#
# strict_arg — only enforced when hisnos.strict=1
strict_arg=nokaslr
strict_arg=rd.break
strict_arg=rd.shell
strict_arg=single
EOF
        ok "Created /etc/hisnos/cmdline-policy.conf"
    else
        log "/etc/hisnos/cmdline-policy.conf already exists"
    fi
fi

# ─── Verify dracut configuration ─────────────────────────────────────────────
DRACUT_CONF="/etc/dracut.conf.d/90-hisnos.conf"
log "Writing dracut config: $DRACUT_CONF"
if [[ "$DRY_RUN" != "true" ]]; then
    mkdir -p /etc/dracut.conf.d
    cat > "$DRACUT_CONF" <<'EOF'
# HisnOS dracut configuration
# Generated by dracut/install-dracut-module.sh

# Always include the HisnOS module
add_dracutmodules+=" 95hisnos "

# Ensure bash is available (recovery shell needs it)
add_dracutmodules+=" bash "

# Include key binaries for recovery
install_items+=" /bin/strace /usr/bin/less /usr/bin/tmux "

# Compress initramfs with zstd for fast decompression
compress="zstd"

# Include microcode
early_microcode="yes"

# Hostonly mode: smaller initramfs for installed system
# Set to "no" for generic (livemedia) initramfs
hostonly="yes"
EOF
    ok "Dracut config written"
fi

# ─── Rebuild initramfs ────────────────────────────────────────────────────────
if [[ "$NO_REBUILD" == "true" ]]; then
    warn "Skipping initramfs rebuild (--no-rebuild)"
    log "Rebuild manually: dracut --force --add 95hisnos"
else
    log "Rebuilding initramfs (this may take 30-90 seconds)..."
    KERNEL_VERSION="$(uname -r)"
    if [[ "$DRY_RUN" == "true" ]]; then
        dry "dracut --force --add 95hisnos -k $KERNEL_VERSION"
    else
        if dracut --force --add "95hisnos" \
            --kernel-version "$KERNEL_VERSION" \
            2>&1 | grep -v "^$"; then
            ok "Initramfs rebuilt for kernel $KERNEL_VERSION"
        else
            warn "dracut returned non-zero — check output above"
        fi
    fi
fi

# ─── Summary ─────────────────────────────────────────────────────────────────
echo ""
echo -e "${W}${G}═══ HisnOS Dracut Module Installed ═══${X}"
echo "  Module:   $MODULE_DST"
echo "  Config:   $DRACUT_CONF"
echo "  Policy:   /etc/hisnos/cmdline-policy.conf"
echo ""
echo "  Recovery mode: add 'hisnos.recovery=1' to kernel cmdline"
echo "  Safe mode:     add 'hisnos.safemode=1' to kernel cmdline"
echo "  Strict mode:   add 'hisnos.strict=1' to enforce all policy"
echo ""
